
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ITEM = 20;
  public static final int DATE = 23;
  public static final int END = 13;
  public static final int ERROR = 6;
  public static final int SECTION = 16;
  public static final int OPERATOR = 5;
  public static final int BEGIN = 12;
  public static final int MAKE = 17;
  public static final int DOCCLASS = 10;
  public static final int EOF = 0;
  public static final int TITLE = 14;
  public static final int FUNC = 7;
  public static final int COMMENT = 9;
  public static final int NEWLINE = 22;
  public static final int MATHMODE = 19;
  public static final int error = 1;
  public static final int BODY = 3;
  public static final int PACKAGE = 11;
  public static final int TEXT = 2;
  public static final int NM = 4;
  public static final int SUBTITLE = 15;
  public static final int LABEL = 21;
  public static final int VAR = 8;
  public static final int BF = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TEXT",
  "BODY",
  "NM",
  "OPERATOR",
  "ERROR",
  "FUNC",
  "VAR",
  "COMMENT",
  "DOCCLASS",
  "PACKAGE",
  "BEGIN",
  "END",
  "TITLE",
  "SUBTITLE",
  "SECTION",
  "MAKE",
  "BF",
  "MATHMODE",
  "ITEM",
  "LABEL",
  "NEWLINE",
  "DATE"
  };
}

